stages:
- app-build
- app-image-build
- app-deploy

build-nodejs-app:
    stage: app-build
    image: node:18.12.1
    script:
        - node -v
        - npm -v
        - npm cache clean --force
        - npm install
    artifacts:
        paths:
            - node_modules/