stages:
- app-build
- app-image-build
- app-deploy

variables:
    APP_NAME: "timeoff-management-app"
    APP_VERSION: $CI_PIPELINE_IID

build-nodejs-app:
    stage: app-build
    image: node:18.12.1
    script:
        - node -v
        - npm -v
        - npm cache clean --force
        - npm install
        - echo $CI_PIPELINE_IID
    artifacts:
        paths:
            - node_modules/

build-docker-image:
    stage: app-image-build
    image: docker:20.10.21
    services:
        - docker:20.10.21-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY/uditrpanchal/timeoff-management -t $CI_REGISTRY/uditrpanchal/timeoff-management:$APP_VERSION .
        - docker image ls
        - docker push --all-tags $CI_REGISTRY/uditrpanchal/timeoff-management


