FROM amazon/aws-cli:2.9.7

RUN yum -y install tar gzip && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256" && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl