---
apiVersion: v1
kind: Service
metadata:
  name: external-timeoff-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:574887112345:certificate/15ba1094-1c2e-4c83-a17f-e31dfb9c2d31
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
